backend:
  name: github
  repo: suraj745/Netlify-CMS

media_folder: /public/images
public_folder: /public

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
